# Generated by Django 4.2.1 on 2023-06-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_remove_player_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
