# Generated by Django 4.2.1 on 2023-06-04 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_player_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='game',
        ),
    ]
